//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingAPZ.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesProducts
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TypeWorkId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
        public virtual TypeWork TypeWork { get; set; }
    }
}
